version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - number-db:/app/data
    networks:
      - number-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - number-network

volumes:
  number-db:

networks:
  number-network:
    driver: bridge